# Generated by Django 5.1.3 on 2024-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='fio',
            field=models.CharField(max_length=100, verbose_name='Имя\\Фамилия\\Кабинет'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='thefuckingthing',
            field=models.TextField(verbose_name='Опишите, пожалуйста, вашу проблему'),
        ),
    ]
